version: 2

updates:
  - package-ecosystem: gitsubmodule
    schedule:
        interval: "monthly"
    directory: /
    allow:
      - dependency-name: "Submodules/PelePhysics"
      - dependency-name: "Submodules/qslim"

  - package-ecosystem: github-actions
    schedule:
        interval: "monthly"
    directory: /
